# ============================================================
#  ACTIVE PROFILE - change to 'prod' for MySQL
# ============================================================
spring.profiles.active=${SPRING_PROFILE:dev}

# Server
server.port=${PORT:8080}
